CREATE TRIGGER UPD_SYSVIEW_PRIV INSTEAD OF UPDATE OF PRIV on SYSVIEW 
        BEGIN
        UPDATE SYSINFO SET ID_PRIV =
		( SELECT ID FROM PRIV WHERE NAME=NEW.PRIV ) 
        WHERE SYSVIEW.FQDN=NEW.FQDN;
        END;

